import { PartListImage } from "../image-utils";
import { colorEntryToHex } from "../utils";

declare const JSZip: any;

export async function generateOpenSCAD(image: PartListImage, filename: string) {
    // Dynamically load JSZip if not already loaded
    await loadJSZip();
    
    const zip = new JSZip();
    
    // Generate one monochrome image per color
    for (let colorIdx = 0; colorIdx < image.partList.length; colorIdx++) {
        const color = image.partList[colorIdx];
        const imageData = createMonochromeImage(image, colorIdx);
        const blob = await canvasToBlob(imageData);
        zip.file(`color_${colorIdx}_${sanitizeFilename(color.target.name)}.png`, blob);
    }
    
    // Generate the OpenSCAD file
    const scadContent = createOpenSCADFile(image);
    zip.file(`${filename}.scad`, scadContent);
    
    // Generate and download the ZIP
    const zipBlob = await zip.generateAsync({ type: "blob" });
    downloadBlob(zipBlob, `${filename}_openscad.zip`);
}

function createMonochromeImage(image: PartListImage, colorIdx: number): HTMLCanvasElement {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    // Create black and white image
    const imageData = ctx.createImageData(image.width, image.height);
    
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            const idx = (y * image.width + x) * 4;
            const isColorPixel = image.pixels[y][x] === colorIdx;
            
            // White for this color, black otherwise
            const value = isColorPixel ? 255 : 0;
            imageData.data[idx] = value;     // R
            imageData.data[idx + 1] = value; // G
            imageData.data[idx + 2] = value; // B
            imageData.data[idx + 3] = 255;   // A
        }
    }
    
    ctx.putImageData(imageData, 0, 0);
    return canvas;
}

function createOpenSCADFile(image: PartListImage): string {
    const layers: string[] = [];
    
    for (let colorIdx = 0; colorIdx < image.partList.length; colorIdx++) {
        const color = image.partList[colorIdx];
        const hex = colorEntryToHex(color.target);
        const r = parseInt(hex.substring(1, 3), 16) / 255;
        const g = parseInt(hex.substring(3, 5), 16) / 255;
        const b = parseInt(hex.substring(5, 7), 16) / 255;
        
        const filename = `color_${colorIdx}_${sanitizeFilename(color.target.name)}.png`;
        
        layers.push(`
// ${color.target.name}
color([${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)}])
translate([0, 0, ${colorIdx}])
scale([1, 1, 1])
surface(file = "${filename}", center = true, invert = true);
`);
    }
    
    const scadContent = `// Generated by firaga.io
// 3D representation of image with ${image.partList.length} colors
// Image dimensions: ${image.width}x${image.height}

// Each color is rendered as a heightmap layer

${layers.join('\n')}`;
    
    return scadContent;
}

function sanitizeFilename(name: string): string {
    return name.replace(/[^a-zA-Z0-9_-]/g, '_');
}

async function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
    return new Promise((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to create blob from canvas'));
            }
        }, 'image/png');
    });
}

function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

async function loadJSZip() {
    const tagName = "jszip-script-tag";
    const scriptEl = document.getElementById(tagName);
    if (scriptEl === null) {
        return new Promise<void>((resolve, reject) => {
            const tag = document.createElement("script");
            tag.id = tagName;
            tag.onload = () => resolve();
            tag.onerror = () => reject(new Error('Failed to load JSZip'));
            tag.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
            document.head.appendChild(tag);
        });
    }
}
