import { saveAs } from 'file-saver';
import { PartListImage } from '../image-utils';
import { colorEntryToHex } from '../utils';

declare const JSZip: any;

export type ExportOpenSCADSettings = {
    baseHeight: number;
    pixelHeight: number;
    filename: string;
};

export async function exportOpenSCADMasks(image: PartListImage, settings: ExportOpenSCADSettings): Promise<void> {
    await loadJSZip();
    
    const zip = new JSZip();
    
    // Generate a monochrome PNG for each color
    const colorFiles: string[] = [];
    for (let partIndex = 0; partIndex < image.partList.length; partIndex++) {
        const part = image.partList[partIndex];
        const maskData = await generateColorMask(image, partIndex);
        const fileName = `mask_${sanitizeFilename(part.target.name)}_${partIndex}.png`;
        colorFiles.push(fileName);
        zip.file(fileName, maskData);
    }
    
    // Generate OpenSCAD file
    const scadContent = generateOpenSCADFile(image, settings, colorFiles, image.partList.map(p => ({
        name: p.target.name,
        color: colorEntryToHex(p.target)
    })));
    zip.file(`${settings.filename}.scad`, scadContent);
    
    // Generate README
    const readme = generateReadme(settings);
    zip.file('README.txt', readme);
    
    // Save as zip
    const zipBlob = await zip.generateAsync({ type: 'blob' });
    saveAs(zipBlob, `${settings.filename}_openscad.zip`);
}

function generateColorMask(image: PartListImage, partIndex: number): Promise<Blob> {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d');
    
    if (!ctx) {
        throw new Error('Could not get canvas context');
    }
    
    const imageData = ctx.createImageData(image.width, image.height);
    
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            const idx = (y * image.width + x) * 4;
            const isThisColor = image.pixels[y][x] === partIndex;
            
            // White (255) where pixel should be filled, black (0) otherwise
            const value = isThisColor ? 255 : 0;
            imageData.data[idx] = value;
            imageData.data[idx + 1] = value;
            imageData.data[idx + 2] = value;
            imageData.data[idx + 3] = 255; // Full opacity
        }
    }
    
    ctx.putImageData(imageData, 0, 0);
    
    return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to generate PNG blob'));
            }
        }, 'image/png');
    });
}

function generateOpenSCADFile(
    image: PartListImage,
    settings: ExportOpenSCADSettings,
    maskFiles: string[],
    colors: Array<{ name: string; color: string }>
): string {
    const pixelSize = 1.0; // 1mm per pixel
    const width = image.width * pixelSize;
    const height = image.height * pixelSize;
    
    const colorModules = maskFiles.map((file, idx) => {
        const color = colors[idx];
        const rgbColor = hexToRgb(color.color);
        
        return `
// ${color.name}
module layer_${idx}() {
    color([${rgbColor.r / 255}, ${rgbColor.g / 255}, ${rgbColor.b / 255}])
    translate([0, 0, base_height])
    surface(file = "${file}", center = true, invert = true);
}`;
    }).join('\n');
    
    const layerCalls = maskFiles.map((_, idx) => `layer_${idx}();`).join('\n');
    
    return `// Generated by firaga.io
// Pixel art 3D model using heightmap layers

// Parameters
pixel_size = ${pixelSize}; // mm per pixel
base_height = ${settings.baseHeight}; // mm
pixel_height = ${settings.pixelHeight}; // mm
width = ${width}; // mm
height = ${height}; // mm

// Base layer
color([0.5, 0.5, 0.5])
translate([0, 0, base_height / 2])
cube([width, height, base_height], center = true);

// Color layers
${colorModules}

// Render all layers
${layerCalls}
`;
}

function generateReadme(settings: ExportOpenSCADSettings): string {
    return `OpenSCAD Pixel Art Export - ${settings.filename}
Generated by firaga.io

This archive contains:
1. ${settings.filename}.scad - The main OpenSCAD file
2. mask_*.png - Black and white mask images for each color

To use:
1. Extract all files to the same directory
2. Open ${settings.filename}.scad in OpenSCAD
3. Press F5 to preview or F6 to render
4. Export to STL for 3D printing

Parameters you can adjust in the .scad file:
- pixel_size: Size of each pixel in mm (default: 1mm)
- base_height: Height of the base layer in mm (default: ${settings.baseHeight}mm)
- pixel_height: Height of each pixel above the base in mm (default: ${settings.pixelHeight}mm)

The white areas in each mask image indicate where that color should appear.
`;
}

function sanitizeFilename(name: string): string {
    return name
        .replace(/[^a-zA-Z0-9]/g, '_')
        .replace(/_+/g, '_')
        .toLowerCase();
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16)
    } : { r: 0, g: 0, b: 0 };
}

async function loadJSZip(): Promise<void> {
    if (typeof JSZip !== 'undefined') {
        return;
    }
    
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('Failed to load JSZip'));
        document.head.appendChild(script);
    });
}
