import { PartListImage } from "../image-utils";
import { saveAs } from 'file-saver';

declare const JSZip: typeof import("jszip");

/**
 * Generate an OpenSCAD masks zip file with:
 * - One monochrome (black/white) image per color
 * - An OpenSCAD file that loads all images and combines them into a 3D display
 */
export function generateOpenSCADMasks(image: PartListImage, filename: string) {
    loadOpenSCADLibraries(() => generateOpenSCADMasksWorker(image, filename));
}

async function loadOpenSCADLibraries(func: () => void) {
    const tagName = "jszip-script-tag";
    const scriptEl = document.getElementById(tagName);
    if (scriptEl === null) {
        const tag = document.createElement("script");
        tag.id = tagName;
        tag.onload = () => {
            func();
        };
        tag.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
        document.head.appendChild(tag);
    } else {
        func();
    }
}

function generateOpenSCADMasksWorker(image: PartListImage, filename: string) {
    const zip = new JSZip();
    
    // Group pixels by color
    const colorGroups = new Map<number, Array<{x: number, y: number}>>();
    
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            const colorIndex = image.pixels[y][x];
            if (colorIndex !== undefined && colorIndex >= 0) {
                if (!colorGroups.has(colorIndex)) {
                    colorGroups.set(colorIndex, []);
                }
                colorGroups.get(colorIndex)!.push({x, y});
            }
        }
    }
    
    // Generate one PNG per color
    const scadLayers: string[] = [];
    let colorIdx = 0;
    
    colorGroups.forEach((pixels, colorIndex) => {
        const color = image.partList[colorIndex];
        if (!color) return;
        
        // Create a black and white canvas for this color
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        
        // Fill with white (background)
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // Draw black pixels where this color appears
        ctx.fillStyle = 'black';
        pixels.forEach(({x, y}) => {
            ctx.fillRect(x, y, 1, 1);
        });
        
        // Convert canvas to PNG and add to zip
        const pngFilename = `mask_${colorIdx}_${sanitizeFilename(color.target.name)}.png`;
        canvas.toBlob((blob) => {
            if (blob) {
                zip.file(pngFilename, blob);
            }
        });
        
        // Add layer to OpenSCAD file
        const colorHex = rgbToHex(color.target.r, color.target.g, color.target.b);
        const colorVec = `[${(color.target.r / 255).toFixed(3)}, ${(color.target.g / 255).toFixed(3)}, ${(color.target.b / 255).toFixed(3)}]`;
        
        scadLayers.push(`// ${color.target.name} (${color.target.code || 'N/A'})
color(${colorVec})
  translate([0, 0, ${colorIdx}])
    surface(file = "${pngFilename}", center = true, invert = true);`);
        
        colorIdx++;
    });
    
    // Generate the OpenSCAD file
    const scadContent = `// OpenSCAD file for ${filename}
// Generated by firaga.io
// Each color layer is represented as a heightmap surface

$fn = 50; // Resolution

// Stack all color layers
union() {
${scadLayers.map(layer => '  ' + layer.split('\n').join('\n  ')).join('\n\n')}
}
`;
    
    zip.file(`${filename}.scad`, scadContent);
    
    // Add a README
    const readme = `# ${filename} - OpenSCAD Masks Export

This archive contains:
- One PNG mask file per color (black = present, white = absent)
- An OpenSCAD (.scad) file that loads and combines all masks into a 3D model

## Usage

1. Extract all files to a folder
2. Open the .scad file in OpenSCAD (https://openscad.org/)
3. Press F5 to preview or F6 to render
4. Export as STL if desired (File > Export > Export as STL)

## Notes

- Each color is rendered as a separate layer at a different Z height
- The heightmap functionality is used to convert the 2D masks into 3D surfaces
- You can adjust the $fn variable in the .scad file for higher/lower resolution

Generated by firaga.io - https://firaga.io/
`;
    
    zip.file("README.md", readme);
    
    // Generate and download the zip
    setTimeout(() => {
        zip.generateAsync({ type: "blob" }).then((content: Blob) => {
            saveAs(content, `${filename}_openscad.zip`);
        });
    }, 500); // Wait a bit for canvas.toBlob to complete
}

function sanitizeFilename(name: string): string {
    return name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
}

function rgbToHex(r: number, g: number, b: number): string {
    const toHex = (n: number) => {
        const hex = Math.round(n).toString(16).padStart(2, '0');
        return hex.toUpperCase();
    };
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}
