import { saveAs } from 'file-saver';
import { PartListImage } from '../image-utils';

export async function generateOpenSCADMasks(image: PartListImage, filename: string) {
    // Create a simple implementation using manual zip generation
    // For a proper implementation, we'd need JSZip library
    // For now, let's create individual files
    
    const masks = createColorMasks(image);
    const scadContent = createOpenSCADFile(image, masks);
    
    // Since we can't easily create a zip without a library, let's save the SCAD file
    // and provide instructions for the masks
    // In a real implementation, we'd use JSZip to bundle everything
    
    // For now, create a single SCAD file with embedded data
    const blob = new Blob([scadContent], { type: 'text/plain' });
    saveAs(blob, `${filename}.scad`);
    
    // Save each mask as a separate PNG file
    for (const mask of masks) {
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const ctx = canvas.getContext('2d')!;
        const imageData = ctx.createImageData(image.width, image.height);
        
        for (let y = 0; y < image.height; y++) {
            for (let x = 0; x < image.width; x++) {
                const idx = (y * image.width + x) * 4;
                const value = mask.data[y][x] ? 255 : 0;
                imageData.data[idx] = value;
                imageData.data[idx + 1] = value;
                imageData.data[idx + 2] = value;
                imageData.data[idx + 3] = 255;
            }
        }
        
        ctx.putImageData(imageData, 0, 0);
        canvas.toBlob((blob) => {
            if (blob) {
                saveAs(blob, `${filename}_${mask.name}.png`);
            }
        });
    }
}

type ColorMask = {
    name: string;
    colorName: string;
    data: boolean[][];
};

function createColorMasks(image: PartListImage): ColorMask[] {
    const masks: ColorMask[] = [];
    
    image.partList.forEach((entry, colorIndex) => {
        const mask: boolean[][] = [];
        
        for (let y = 0; y < image.height; y++) {
            const row: boolean[] = [];
            for (let x = 0; x < image.width; x++) {
                row.push(image.pixels[y][x] === colorIndex);
            }
            mask.push(row);
        }
        
        masks.push({
            name: `color_${colorIndex}`,
            colorName: entry.target.name,
            data: mask
        });
    });
    
    return masks;
}

function createOpenSCADFile(image: PartListImage, masks: ColorMask[]): string {
    const voxelSize = 1; // Size of each voxel
    const layerHeight = 1; // Height per layer
    
    let scadContent = `// OpenSCAD file for ${image.width}x${image.height} image
// Generated by Firaga.io

// Parameters
voxel_size = ${voxelSize};
layer_height = ${layerHeight};
image_width = ${image.width};
image_height = ${image.height};

// Helper module to create a heightmap from image
module color_layer(image_file, color_name) {
    // Load the image and create a surface based on white pixels
    surface(file = image_file, center = true, invert = true);
}

// Main model
union() {
`;
    
    // Add each color layer
    masks.forEach((mask, idx) => {
        const r = image.partList[idx].target.r;
        const g = image.partList[idx].target.g;
        const b = image.partList[idx].target.b;
        
        scadContent += `    // Layer ${idx + 1}: ${mask.colorName}\n`;
        scadContent += `    color([${(r/255).toFixed(3)}, ${(g/255).toFixed(3)}, ${(b/255).toFixed(3)}])\n`;
        scadContent += `    translate([0, 0, ${idx * layerHeight}])\n`;
        scadContent += `    scale([voxel_size, voxel_size, layer_height])\n`;
        scadContent += `    surface(file = "${mask.name}.png", center = true, invert = false);\n\n`;
    });
    
    scadContent += `}

// Instructions:
// 1. Place all ${masks.length} mask PNG files in the same directory as this .scad file
// 2. Open this file in OpenSCAD
// 3. Render (F6) to create the 3D model
// 4. Export as STL or other 3D format

// Mask files needed:
`;
    
    masks.forEach(mask => {
        scadContent += `// - ${mask.name}.png (${mask.colorName})\n`;
    });
    
    return scadContent;
}
