import { PartListImage } from "./image-utils";
import { colorEntryToHex } from "./utils";

declare const JSZip: any;

export type Export3DSettings = {
    format: "3mf" | "openscad-masks";
    filename: string;
    pixelHeight: number;
};

/**
 * Main export function that handles both 3MF and OpenSCAD formats
 */
export async function export3D(image: PartListImage, settings: Export3DSettings) {
    if (settings.format === "3mf") {
        await export3MF(image, settings);
    } else {
        await exportOpenSCADMasks(image, settings);
    }
}

/**
 * Export as 3MF triangle mesh with separate material shapes for each color
 */
async function export3MF(image: PartListImage, settings: Export3DSettings) {
    await loadJSZip();

    const zip = new JSZip();
    
    // Create the 3MF model
    const modelXML = generate3MFModel(image, settings.pixelHeight);
    
    // Add required 3MF files
    zip.file("3D/3dmodel.model", modelXML);
    zip.file("[Content_Types].xml", getContentTypesXML());
    zip.file("_rels/.rels", getRelsXML());
    
    // Generate and download the zip as .3mf
    const blob = await zip.generateAsync({ type: "blob" });
    downloadBlob(blob, `${settings.filename}.3mf`);
}

/**
 * Export as OpenSCAD masks format (zip with images + .scad file)
 */
async function exportOpenSCADMasks(image: PartListImage, settings: Export3DSettings) {
    await loadJSZip();

    const zip = new JSZip();
    
    // Create one black/white image per color
    const imagePromises = image.partList.map(async (part, idx) => {
        const canvas = createMaskImage(image, idx);
        const blob = await canvasToBlob(canvas);
        zip.file(`mask_${idx}_${sanitizeFilename(part.target.name)}.png`, blob);
    });
    
    await Promise.all(imagePromises);
    
    // Create the OpenSCAD file
    const scadContent = generateOpenSCADFile(image, settings.pixelHeight);
    zip.file(`${settings.filename}.scad`, scadContent);
    
    // Generate and download the zip
    const blob = await zip.generateAsync({ type: "blob" });
    downloadBlob(blob, `${settings.filename}_openscad.zip`);
}

/**
 * Create a black/white mask image for a specific color layer
 */
function createMaskImage(image: PartListImage, partIndex: number): HTMLCanvasElement {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    // Fill with white background
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Draw black pixels where this color appears
    ctx.fillStyle = 'black';
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            if (image.pixels[y][x] === partIndex) {
                ctx.fillRect(x, y, 1, 1);
            }
        }
    }
    
    return canvas;
}

/**
 * Generate OpenSCAD file content that loads heightmaps and combines them
 */
function generateOpenSCADFile(image: PartListImage, pixelHeight: number): string {
    const lines: string[] = [];
    
    lines.push('// Generated by firaga.io');
    lines.push('// OpenSCAD 3D model from pixel art');
    lines.push('');
    lines.push(`pixel_size = 1; // Size of each pixel in mm`);
    lines.push(`pixel_height = ${pixelHeight}; // Height of each layer in mm`);
    lines.push(`image_width = ${image.width};`);
    lines.push(`image_height = ${image.height};`);
    lines.push('');
    lines.push('union() {');
    
    image.partList.forEach((part, idx) => {
        const color = colorEntryToHex(part.target);
        const rgb = hexToRgb(color);
        const filename = `mask_${idx}_${sanitizeFilename(part.target.name)}.png`;
        
        lines.push(`    // ${part.target.name} (${part.count} pixels)`);
        lines.push(`    color([${rgb.r}, ${rgb.g}, ${rgb.b}])`);
        lines.push(`    translate([0, 0, ${idx * pixelHeight}])`);
        lines.push(`    scale([pixel_size, pixel_size, pixel_height])`);
        lines.push(`    surface(file = "${filename}", center = false, invert = true);`);
        lines.push('');
    });
    
    lines.push('}');
    
    return lines.join('\n');
}

/**
 * Generate 3MF model XML with separate meshes for each color
 */
function generate3MFModel(image: PartListImage, pixelHeight: number): string {
    const lines: string[] = [];
    
    lines.push('<?xml version="1.0" encoding="UTF-8"?>');
    lines.push('<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">');
    lines.push('  <resources>');
    
    // Define base materials (colors)
    lines.push('    <basematerials id="1">');
    image.partList.forEach((part, idx) => {
        const color = colorEntryToHex(part.target);
        const rgb = hexToRgb(color);
        lines.push(`      <base name="${escapeXML(part.target.name)}" displaycolor="${color.substring(1)}" />`);
    });
    lines.push('    </basematerials>');
    
    // Create mesh objects for each color
    image.partList.forEach((part, idx) => {
        const mesh = generate3DMesh(image, idx, pixelHeight);
        lines.push(`    <object id="${idx + 2}" type="model">`);
        lines.push('      <mesh>');
        lines.push('        <vertices>');
        mesh.vertices.forEach(v => {
            lines.push(`          <vertex x="${v.x}" y="${v.y}" z="${v.z}" />`);
        });
        lines.push('        </vertices>');
        lines.push('        <triangles>');
        mesh.triangles.forEach(t => {
            lines.push(`          <triangle v1="${t.v1}" v2="${t.v2}" v3="${t.v3}" pid="1" p1="${idx}" />`);
        });
        lines.push('        </triangles>');
        lines.push('      </mesh>');
        lines.push('    </object>');
    });
    
    lines.push('  </resources>');
    lines.push('  <build>');
    
    // Add all objects to the build
    image.partList.forEach((part, idx) => {
        lines.push(`    <item objectid="${idx + 2}" />`);
    });
    
    lines.push('  </build>');
    lines.push('</model>');
    
    return lines.join('\n');
}

/**
 * Generate a 3D mesh (vertices and triangles) for a specific color layer
 */
function generate3DMesh(image: PartListImage, partIndex: number, height: number): { vertices: Array<{x: number, y: number, z: number}>, triangles: Array<{v1: number, v2: number, v3: number}> } {
    const vertices: Array<{x: number, y: number, z: number}> = [];
    const triangles: Array<{v1: number, v2: number, v3: number}> = [];
    
    // Create a box (extruded pixel) for each pixel of this color
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            if (image.pixels[y][x] === partIndex) {
                const baseIdx = vertices.length;
                const z = partIndex * height;
                
                // Create 8 vertices for a box (pixel as a cube)
                vertices.push(
                    { x: x, y: y, z: z },                           // 0: bottom-left-front
                    { x: x + 1, y: y, z: z },                       // 1: bottom-right-front
                    { x: x + 1, y: y + 1, z: z },                   // 2: bottom-right-back
                    { x: x, y: y + 1, z: z },                       // 3: bottom-left-back
                    { x: x, y: y, z: z + height },                  // 4: top-left-front
                    { x: x + 1, y: y, z: z + height },              // 5: top-right-front
                    { x: x + 1, y: y + 1, z: z + height },          // 6: top-right-back
                    { x: x, y: y + 1, z: z + height }               // 7: top-left-back
                );
                
                // Create 12 triangles (2 per face, 6 faces)
                // Bottom face
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 2, v3: baseIdx + 1 });
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 3, v3: baseIdx + 2 });
                
                // Top face
                triangles.push({ v1: baseIdx + 4, v2: baseIdx + 5, v3: baseIdx + 6 });
                triangles.push({ v1: baseIdx + 4, v2: baseIdx + 6, v3: baseIdx + 7 });
                
                // Front face
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 1, v3: baseIdx + 5 });
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 5, v3: baseIdx + 4 });
                
                // Back face
                triangles.push({ v1: baseIdx + 3, v2: baseIdx + 7, v3: baseIdx + 6 });
                triangles.push({ v1: baseIdx + 3, v2: baseIdx + 6, v3: baseIdx + 2 });
                
                // Left face
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 4, v3: baseIdx + 7 });
                triangles.push({ v1: baseIdx + 0, v2: baseIdx + 7, v3: baseIdx + 3 });
                
                // Right face
                triangles.push({ v1: baseIdx + 1, v2: baseIdx + 2, v3: baseIdx + 6 });
                triangles.push({ v1: baseIdx + 1, v2: baseIdx + 6, v3: baseIdx + 5 });
            }
        }
    }
    
    return { vertices, triangles };
}

/**
 * Required 3MF [Content_Types].xml file
 */
function getContentTypesXML(): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml" />
</Types>`;
}

/**
 * Required 3MF _rels/.rels file
 */
function getRelsXML(): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>`;
}

/**
 * Utility functions
 */

function hexToRgb(hex: string): { r: number, g: number, b: number } {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16) / 255,
        g: parseInt(result[2], 16) / 255,
        b: parseInt(result[3], 16) / 255
    } : { r: 0, g: 0, b: 0 };
}

function escapeXML(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

function sanitizeFilename(name: string): string {
    return name.replace(/[^a-zA-Z0-9_-]/g, '_');
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
    return new Promise((resolve, reject) => {
        canvas.toBlob(blob => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to convert canvas to blob'));
            }
        });
    });
}

function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

async function loadJSZip() {
    const tagName = "jszip-script-tag";
    if (document.getElementById(tagName) === null) {
        return new Promise<void>((resolve) => {
            const tag = document.createElement("script");
            tag.id = tagName;
            tag.onload = () => resolve();
            tag.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
            document.head.appendChild(tag);
        });
    }
}
