import { PartListImage } from './image-utils';
import { saveAs } from 'file-saver';

export interface OpenSCADSettings {
    pitch: number;
    height: number;
    filename: string;
}

export async function generateOpenSCADMasks(
    image: PartListImage,
    settings: OpenSCADSettings
): Promise<void> {
    const { pitch, height, filename } = settings;
    const JSZip = (await import('jszip')).default;
    const zip = new JSZip();
    
    // Generate one mask image per color
    const maskFiles: string[] = [];
    for (let i = 0; i < image.partList.length; i++) {
        const part = image.partList[i];
        const maskFilename = `mask_${i}_${sanitizeFilename(part.target.name)}.png`;
        maskFiles.push(maskFilename);
        
        const maskImage = generateMaskImage(image, i);
        const blob = await canvasToBlob(maskImage);
        zip.file(maskFilename, blob);
    }
    
    // Generate OpenSCAD file
    const scadContent = generateOpenSCADFile(image, maskFiles, pitch, height);
    zip.file(`${filename}.scad`, scadContent);
    
    // Generate README
    const readme = generateReadme(pitch, height);
    zip.file('README.txt', readme);
    
    const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
    saveAs(blob, `${filename}_openscad.zip`);
}

function generateMaskImage(image: PartListImage, partIndex: number): HTMLCanvasElement {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    const imageData = ctx.createImageData(image.width, image.height);
    
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            const idx = (y * image.width + x) * 4;
            const isThisColor = image.pixels[y][x] === partIndex;
            const value = isThisColor ? 0 : 255; // Black for filled, white for empty
            
            imageData.data[idx] = value;
            imageData.data[idx + 1] = value;
            imageData.data[idx + 2] = value;
            imageData.data[idx + 3] = 255;
        }
    }
    
    ctx.putImageData(imageData, 0, 0);
    return canvas;
}

function generateOpenSCADFile(
    image: PartListImage,
    maskFiles: string[],
    pitch: number,
    height: number
): string {
    let scad = '// Generated by firaga.io\n';
    scad += '// 3D representation using heightmap surface() modules\n\n';
    scad += `// Settings\n`;
    scad += `pitch = ${pitch}; // mm per pixel\n`;
    scad += `bead_height = ${height}; // mm height of each bead\n`;
    scad += `image_width = ${image.width};\n`;
    scad += `image_height = ${image.height};\n\n`;
    
    scad += '// Colors (RGB values normalized to 0-1)\n';
    image.partList.forEach((part, idx) => {
        const r = (part.target.r / 255).toFixed(3);
        const g = (part.target.g / 255).toFixed(3);
        const b = (part.target.b / 255).toFixed(3);
        scad += `color_${idx} = [${r}, ${g}, ${b}]; // ${part.target.name}\n`;
    });
    scad += '\n';
    
    scad += '// Render all layers\n';
    scad += 'union() {\n';
    
    image.partList.forEach((part, idx) => {
        scad += `  // ${part.target.name}\n`;
        scad += `  color(color_${idx}) {\n`;
        scad += `    scale([pitch, pitch, bead_height]) {\n`;
        scad += `      surface(file = "${maskFiles[idx]}", center = true, invert = true);\n`;
        scad += `    }\n`;
        scad += `  }\n`;
    });
    
    scad += '}\n';
    
    return scad;
}

function generateReadme(pitch: number, height: number): string {
    return `OpenSCAD Heightmap Export
========================

This archive contains:
- Mask images (PNG files) - one per color, showing which pixels use that color
- An OpenSCAD file (.scad) that combines all masks into a 3D model

Settings:
- Pitch: ${pitch} mm per pixel
- Height: ${height} mm per bead

Usage:
1. Install OpenSCAD from https://openscad.org/
2. Open the .scad file in OpenSCAD
3. Press F5 to preview or F6 to render
4. Export to STL via File > Export > Export as STL

Notes:
- Black pixels in mask images represent filled positions
- White pixels represent empty positions
- Each color layer is rendered separately and combined with union()
`;
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
    return new Promise((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to convert canvas to blob'));
            }
        });
    });
}

function sanitizeFilename(name: string): string {
    return name.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
}
