import { saveAs } from 'file-saver';
import { PartListImage } from './image-utils';
import { colorEntryToHex } from './utils';
import { ThreeDSettings } from './3d-generator-3mf';

declare const JSZip: any;

export async function generateOpenSCADMasks(image: PartListImage, settings: ThreeDSettings) {
    // Load JSZip dynamically
    await loadJSZip();
    
    const zip = new JSZip();
    const voxelSize = settings.pitch * 25.4; // Convert pitch from inches to mm
    const voxelHeight = 2.0; // Height in mm
    
    // Create one mask image per color
    const colorMasks: Map<string, { name: string, data: ImageData }> = new Map();
    
    image.partList.forEach((part, index) => {
        const colorHex = colorEntryToHex(part.target);
        const colorName = part.target.name.replace(/[^a-zA-Z0-9]/g, '_');
        
        // Create a canvas for this color's mask
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const ctx = canvas.getContext('2d')!;
        const imageData = ctx.createImageData(image.width, image.height);
        
        // Fill the mask - white where this color appears, black elsewhere
        for (let y = 0; y < image.height; y++) {
            for (let x = 0; x < image.width; x++) {
                const pixelIndex = image.pixels[y][x];
                const offset = (y * image.width + x) * 4;
                
                if (pixelIndex === index) {
                    // White pixel (255, 255, 255)
                    imageData.data[offset] = 255;
                    imageData.data[offset + 1] = 255;
                    imageData.data[offset + 2] = 255;
                    imageData.data[offset + 3] = 255;
                } else {
                    // Black pixel (0, 0, 0)
                    imageData.data[offset] = 0;
                    imageData.data[offset + 1] = 0;
                    imageData.data[offset + 2] = 0;
                    imageData.data[offset + 3] = 255;
                }
            }
        }
        
        colorMasks.set(colorHex, { name: colorName, data: imageData });
    });
    
    // Convert ImageData to PNG and add to zip
    const colorFiles: Array<{ name: string, hex: string }> = [];
    for (const [colorHex, mask] of colorMasks.entries()) {
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const ctx = canvas.getContext('2d')!;
        ctx.putImageData(mask.data, 0, 0);
        
        // Convert canvas to blob
        const blob = await new Promise<Blob>((resolve) => {
            canvas.toBlob((b) => resolve(b!), 'image/png');
        });
        
        const filename = `mask_${mask.name}.png`;
        zip.file(filename, blob);
        colorFiles.push({ name: filename, hex: colorHex });
    }
    
    // Generate OpenSCAD file
    let scadContent = '// Generated by firaga.io\n';
    scadContent += '// 3D representation of pixel art\n\n';
    scadContent += `voxel_size = ${voxelSize}; // mm\n`;
    scadContent += `voxel_height = ${voxelHeight}; // mm\n`;
    scadContent += `image_width = ${image.width};\n`;
    scadContent += `image_height = ${image.height};\n\n`;
    
    scadContent += 'union() {\n';
    
    colorFiles.forEach((file, index) => {
        const colorRGB = hexToRgb(file.hex);
        scadContent += `  // Color: ${file.name}\n`;
        scadContent += `  color([${colorRGB.r / 255}, ${colorRGB.g / 255}, ${colorRGB.b / 255}]) {\n`;
        scadContent += `    scale([voxel_size, voxel_size, voxel_height / 255])\n`;
        scadContent += `    surface(file = "${file.name}", center = false, invert = true);\n`;
        scadContent += `  }\n\n`;
    });
    
    scadContent += '}\n';
    
    zip.file('model.scad', scadContent);
    
    // Generate README
    const readme = `3D Model Export from firaga.io
    
This ZIP file contains:
- One PNG image per color (black/white masks)
- model.scad: OpenSCAD file to generate the 3D model

To use:
1. Install OpenSCAD (https://openscad.org/)
2. Extract all files to a folder
3. Open model.scad in OpenSCAD
4. Render and export to STL

Settings:
- Voxel size: ${voxelSize} mm
- Voxel height: ${voxelHeight} mm
- Image dimensions: ${image.width} x ${image.height} pixels
`;
    
    zip.file('README.txt', readme);
    
    // Generate and download the zip file
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${settings.filename}_openscad.zip`);
}

function hexToRgb(hex: string): { r: number, g: number, b: number } {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16)
    } : { r: 0, g: 0, b: 0 };
}

async function loadJSZip() {
    const tagName = "jszip-script-tag";
    const scriptEl = document.getElementById(tagName);
    if (scriptEl === null) {
        return new Promise<void>((resolve) => {
            const tag = document.createElement("script");
            tag.id = tagName;
            tag.onload = () => resolve();
            tag.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
            document.head.appendChild(tag);
        });
    }
}
