import { PartListImage } from "./image-utils";
import { colorEntryToHex } from "./utils";

declare const JSZip: any;

export interface ExportOpenSCADSettings {
    pitch: number;
    height: number;
    filename: string;
}

export async function exportOpenSCADMasks(image: PartListImage, settings: ExportOpenSCADSettings): Promise<void> {
    await loadJSZip();
    
    const zip = new JSZip();
    
    const scadContent = generateOpenSCADFile(image, settings);
    zip.file(`${settings.filename}.scad`, scadContent);
    
    for (let partIndex = 0; partIndex < image.partList.length; partIndex++) {
        const part = image.partList[partIndex];
        const imageData = generateMaskImage(image, partIndex);
        const blob = await canvasToBlob(imageData);
        const filename = sanitizeFilename(`${part.target.name}_${partIndex}.png`);
        zip.file(filename, blob);
    }
    
    const zipBlob = await zip.generateAsync({ type: "blob" });
    downloadFile(zipBlob, `${settings.filename}_openscad.zip`);
}

async function loadJSZip(): Promise<void> {
    const tagName = "jszip-script-tag";
    const scriptEl = document.getElementById(tagName);
    
    if (scriptEl !== null) {
        return Promise.resolve();
    }
    
    return new Promise<void>((resolve) => {
        const tag = document.createElement("script");
        tag.id = tagName;
        tag.onload = () => resolve();
        tag.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
        document.head.appendChild(tag);
    });
}

function generateOpenSCADFile(image: PartListImage, settings: ExportOpenSCADSettings): string {
    const pitch = settings.pitch;
    const height = settings.height;
    const layers: string[] = [];
    
    for (let partIndex = 0; partIndex < image.partList.length; partIndex++) {
        const part = image.partList[partIndex];
        const filename = sanitizeFilename(`${part.target.name}_${partIndex}.png`);
        const hexColor = colorEntryToHex(part.target);
        const r = parseInt(hexColor.substring(1, 3), 16) / 255;
        const g = parseInt(hexColor.substring(3, 5), 16) / 255;
        const b = parseInt(hexColor.substring(5, 7), 16) / 255;
        
        layers.push(`
// ${part.target.name}
color([${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)}])
translate([0, 0, ${partIndex * height}])
linear_extrude(height = ${height})
scale([${pitch}, ${pitch}])
surface(file = "${filename}", center = true, invert = true);
`);
    }
    
    const scadContent = `// Generated by firaga.io
// Image: ${settings.filename}
// Pitch: ${pitch}mm
// Height: ${height}mm per layer

$fn = 50;

union() {
${layers.join('\n')}
}
`;
    
    return scadContent;
}

function generateMaskImage(image: PartListImage, partIndex: number): HTMLCanvasElement {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    const imageData = ctx.createImageData(image.width, image.height);
    
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            const idx = (y * image.width + x) * 4;
            const isColorPixel = image.pixels[y][x] === partIndex;
            const value = isColorPixel ? 255 : 0;
            
            imageData.data[idx] = value;
            imageData.data[idx + 1] = value;
            imageData.data[idx + 2] = value;
            imageData.data[idx + 3] = 255;
        }
    }
    
    ctx.putImageData(imageData, 0, 0);
    return canvas;
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
    return new Promise((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to convert canvas to blob'));
            }
        }, 'image/png');
    });
}

function sanitizeFilename(filename: string): string {
    return filename.replace(/[^a-z0-9_\-\.]/gi, '_');
}

function downloadFile(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
