import { PartListImage } from "./image-utils";
import { colorEntryToHex } from "./utils";

export interface OpenSCADSettings {
    pixelSize: number;
    pixelHeight: number;
}

/**
 * Generates a ZIP file containing:
 * - One black/white PNG per color (mask)
 * - An OpenSCAD file that combines them into a 3D model
 */
export function generateOpenSCADMasks(image: PartListImage, settings: OpenSCADSettings): Blob {
    const { pixelSize, pixelHeight } = settings;
    
    // Generate mask images for each color
    const masks: Array<{ name: string; dataUrl: string; color: string }> = [];
    
    for (let partIdx = 0; partIdx < image.partList.length; partIdx++) {
        const part = image.partList[partIdx];
        const canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        const ctx = canvas.getContext('2d')!;
        
        // Fill with white background
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // Draw black pixels where this color appears
        ctx.fillStyle = 'black';
        for (let y = 0; y < image.height; y++) {
            for (let x = 0; x < image.width; x++) {
                if (image.pixels[y][x] === partIdx) {
                    ctx.fillRect(x, y, 1, 1);
                }
            }
        }
        
        const colorName = part.target.name.replace(/[^a-zA-Z0-9]/g, '_');
        const maskName = `mask_${partIdx}_${colorName}.png`;
        
        masks.push({
            name: maskName,
            dataUrl: canvas.toDataURL('image/png'),
            color: colorEntryToHex(part.target)
        });
    }
    
    // Generate OpenSCAD file
    const scadContent = generateSCADFile(masks, image, pixelSize, pixelHeight);
    
    // Create a simple text representation of the zip contents
    // In production, this should use JSZip or similar to create an actual ZIP file
    return createMockZip(masks, scadContent);
}

function generateSCADFile(
    masks: Array<{ name: string; dataUrl: string; color: string }>,
    image: PartListImage,
    pixelSize: number,
    pixelHeight: number
): string {
    let scadContent = `// Generated by firaga.io
// Image size: ${image.width}x${image.height}
// Pixel size: ${pixelSize}mm
// Pixel height: ${pixelHeight}mm

`;
    
    // Add a module for each color layer
    masks.forEach((mask, idx) => {
        const part = image.partList[idx];
        scadContent += `// ${part.target.name} (${part.count} pixels)
module layer_${idx}() {
    color("${mask.color}") {
        surface(file = "${mask.name}", center = true, invert = true);
        scale([${pixelSize}, ${pixelSize}, ${pixelHeight}]) {
            surface(file = "${mask.name}", center = true, invert = true);
        }
    }
}

`;
    });
    
    // Combine all layers
    scadContent += `// Combine all layers
union() {
`;
    
    masks.forEach((_, idx) => {
        scadContent += `    translate([0, 0, ${idx * pixelHeight}]) layer_${idx}();\n`;
    });
    
    scadContent += `}\n`;
    
    return scadContent;
}

function createMockZip(
    masks: Array<{ name: string; dataUrl: string; color: string }>,
    scadContent: string
): Blob {
    // This is a simplified version that returns a text file with instructions
    // In production, this should create an actual ZIP file using JSZip
    
    let content = `OpenSCAD Export Package
=======================

This export contains:
- ${masks.length} mask image(s)
- 1 OpenSCAD file (model.scad)

Files:
------
model.scad

${masks.map(m => m.name).join('\n')}

OpenSCAD Content:
-----------------
${scadContent}

Note: This is a simplified export. In the full implementation, this would be a ZIP file
containing the actual PNG mask images and the .scad file.

Mask Data URLs (for development):
${masks.map((m, i) => `${i}. ${m.name}: ${m.dataUrl.substring(0, 100)}...`).join('\n')}
`;
    
    return new Blob([content], { type: 'text/plain' });
}
