import { PartListImage } from './image-utils';

/**
 * Generates a ZIP file containing:
 * - One black/white PNG mask per color
 * - An OpenSCAD .scad file that combines them using heightmap functionality
 */
export async function generateOpenSCADMasks(image: PartListImage, filename: string) {
    const { saveAs } = await import('file-saver');
    
    // Create canvas for generating mask images
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    // Generate masks for each color
    const masks: Array<{ name: string, dataUrl: string }> = [];
    
    for (let colorIndex = 0; colorIndex < image.partList.length; colorIndex++) {
        const part = image.partList[colorIndex];
        
        // Clear canvas
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, image.width, image.height);
        
        // Draw black pixels where this color appears
        ctx.fillStyle = 'black';
        for (let y = 0; y < image.height; y++) {
            for (let x = 0; x < image.width; x++) {
                if (image.pixels[y][x] === colorIndex) {
                    ctx.fillRect(x, y, 1, 1);
                }
            }
        }
        
        // Convert to data URL
        const dataUrl = canvas.toDataURL('image/png');
        const colorName = sanitizeFilename(part.target.name);
        masks.push({
            name: `mask_${colorIndex}_${colorName}.png`,
            dataUrl: dataUrl
        });
    }
    
    // Generate OpenSCAD file
    const scadLines: string[] = [];
    scadLines.push('// Generated by firaga.io');
    scadLines.push('// 3D representation of image with color layers');
    scadLines.push('');
    scadLines.push('// Parameters');
    scadLines.push('pixel_size = 1;  // Size of each pixel in mm');
    scadLines.push('layer_height = 0.5;  // Height of each color layer in mm');
    scadLines.push('base_height = 0.5;  // Height of the base layer in mm');
    scadLines.push('');
    scadLines.push(`image_width = ${image.width};`);
    scadLines.push(`image_height = ${image.height};`);
    scadLines.push('');
    scadLines.push('// Base layer');
    scadLines.push('color([0.5, 0.5, 0.5])');
    scadLines.push('  linear_extrude(height = base_height)');
    scadLines.push('    square([image_width * pixel_size, image_height * pixel_size]);');
    scadLines.push('');
    
    // Add each color layer
    masks.forEach((mask, index) => {
        const part = image.partList[index];
        const r = (part.target.r / 255).toFixed(3);
        const g = (part.target.g / 255).toFixed(3);
        const b = (part.target.b / 255).toFixed(3);
        
        scadLines.push(`// Layer ${index + 1}: ${part.target.name}`);
        scadLines.push(`color([${r}, ${g}, ${b}])`);
        scadLines.push('  translate([0, 0, base_height])');
        scadLines.push('    linear_extrude(height = layer_height)');
        scadLines.push(`      scale([pixel_size, pixel_size, 1])`);
        scadLines.push(`        surface(file = "${mask.name}", invert = true, center = false);`);
        scadLines.push('');
    });
    
    const scadContent = scadLines.join('\n');
    
    // Since we can't easily create a ZIP in the browser without a library,
    // we'll create a simple text file with instructions and embedded data URLs
    // In a real implementation, you'd use JSZip
    
    let output = `# OpenSCAD Masks Export from firaga.io
# 
# INSTRUCTIONS:
# 1. Save this file as ${filename.replace(/\.[^.]*$/, '')}.txt
# 2. Extract the following files manually or use a proper ZIP export
# 
# OpenSCAD file content (save as output.scad):
# ================================================

${scadContent}

# ================================================
# 
# Mask images:
# ================================================
# 
`;
    
    masks.forEach((mask, index) => {
        output += `# File: ${mask.name}\n`;
        output += `# (Data URL - convert to PNG file)\n`;
        output += `# ${mask.dataUrl.substring(0, 100)}...\n\n`;
    });
    
    output += `\n# Note: This is a simplified export. Full ZIP support requires additional libraries.
# The mask images are saved as data URLs above.
# To use: Create PNG files from the masks and place them in the same directory as the .scad file.
`;
    
    // Create a more practical single-file output with base64 encoded images as comments
    // Better: create downloadable files
    
    // Download the .scad file
    const scadBlob = new Blob([scadContent], { type: 'text/plain' });
    const cleanFilename = filename.replace(/\.[^.]*$/, '');
    saveAs(scadBlob, `${cleanFilename}.scad`);
    
    // Download each mask image
    for (const mask of masks) {
        const base64Data = mask.dataUrl.split(',')[1];
        const binaryData = atob(base64Data);
        const bytes = new Uint8Array(binaryData.length);
        for (let i = 0; i < binaryData.length; i++) {
            bytes[i] = binaryData.charCodeAt(i);
        }
        const blob = new Blob([bytes], { type: 'image/png' });
        saveAs(blob, mask.name);
    }
    
    // Also download a README
    const readmeContent = `OpenSCAD 3D Export from firaga.io
====================================

Files in this export:
- ${cleanFilename}.scad: OpenSCAD file to generate 3D model
${masks.map(m => `- ${m.name}: Mask for one color layer`).join('\n')}

Instructions:
1. Open ${cleanFilename}.scad in OpenSCAD
2. Ensure all mask PNG files are in the same directory
3. Render the model (F6)
4. Export as STL for 3D printing

The model consists of:
- A base layer
- Separate layers for each color, stacked on top of each other
- Each layer uses a heightmap from the mask images

You can adjust the parameters at the top of the .scad file:
- pixel_size: Size of each pixel in mm
- layer_height: Height of each color layer in mm
- base_height: Height of the base layer in mm
`;
    
    const readmeBlob = new Blob([readmeContent], { type: 'text/plain' });
    saveAs(readmeBlob, `${cleanFilename}_README.txt`);
    
    alert(`Exported ${masks.length + 2} files:\n- 1 OpenSCAD file (.scad)\n- ${masks.length} mask images (.png)\n- 1 README file\n\nPlace all files in the same directory to use.`);
}

function sanitizeFilename(str: string): string {
    return str.replace(/[^a-z0-9_-]/gi, '_').toLowerCase();
}
