import { PartListImage } from './image-utils';
import { saveAs } from 'file-saver';

// Simple implementation to create ZIP files without external library
class SimpleZip {
    private files: Array<{ name: string, data: Uint8Array }> = [];
    
    addFile(name: string, data: Uint8Array) {
        this.files.push({ name, data });
    }
    
    async generate(): Promise<Blob> {
        // For simplicity, we'll create a tar-like archive or just use a different approach
        // Since creating a proper ZIP without a library is complex, let's save files separately
        // or use a simpler container format. 
        // Actually, let's just save the scad file and instructions for now.
        // Better: use data URLs embedded in the SCAD file
        throw new Error("Not implemented - see alternative approach");
    }
}

export async function generateOpenSCADMasks(image: PartListImage, filename: string) {
    // Create mask images as data URLs embedded in the SCAD file
    const maskDataUrls: Array<{ colorIdx: number, name: string, dataUrl: string }> = [];
    
    for (let colorIdx = 0; colorIdx < image.partList.length; colorIdx++) {
        const part = image.partList[colorIdx];
        if (!part) continue;
        
        const maskCanvas = document.createElement('canvas');
        maskCanvas.width = image.width;
        maskCanvas.height = image.height;
        const ctx = maskCanvas.getContext('2d')!;
        
        // Fill with white (background)
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, image.width, image.height);
        
        // Draw black pixels where this color is present
        ctx.fillStyle = 'black';
        for (let y = 0; y < image.height; y++) {
            for (let x = 0; x < image.width; x++) {
                if (image.pixels[y][x] === colorIdx) {
                    ctx.fillRect(x, y, 1, 1);
                }
            }
        }
        
        // Convert to PNG data URL
        const dataUrl = maskCanvas.toDataURL('image/png');
        const safeName = part.name.replace(/[^a-zA-Z0-9]/g, '_');
        
        // Save each mask as a separate file
        const blob = await new Promise<Blob>((resolve) => {
            maskCanvas.toBlob((blob) => {
                resolve(blob!);
            }, 'image/png');
        });
        
        saveAs(blob, `${filename}_mask_${colorIdx}_${safeName}.png`);
        
        maskDataUrls.push({ colorIdx, name: safeName, dataUrl });
    }
    
    // Create the OpenSCAD file with instructions
    const scadContent = generateOpenSCADFile(image, filename);
    const scadBlob = new Blob([scadContent], { type: 'text/plain' });
    saveAs(scadBlob, `${filename}.scad`);
    
    // Create a README with instructions
    const readme = `OpenSCAD Masks Export
======================

Files included:
- ${filename}.scad - The main OpenSCAD file
${maskDataUrls.map(m => `- ${filename}_mask_${m.colorIdx}_${m.name}.png`).join('\n')}

Instructions:
1. Place all PNG mask files in the same directory as the .scad file
2. Open ${filename}.scad in OpenSCAD
3. Render the model (F6)
4. Export as STL or other 3D format

The mask images are black/white PNG files where black pixels indicate 
where that color should appear in the final 3D model.
`;
    
    const readmeBlob = new Blob([readme], { type: 'text/plain' });
    saveAs(readmeBlob, `${filename}_README.txt`);
}

function generateOpenSCADFile(image: PartListImage, filename: string): string {
    const pixelSize = 2.5; // Size of each pixel in mm
    const height = 1.0; // Height of each layer in mm
    
    let scadCode = `// OpenSCAD file generated by Firaga.io
// Image dimensions: ${image.width} x ${image.height}
// 
// Instructions:
// 1. Place all mask PNG files in the same directory as this file
// 2. Open this file in OpenSCAD
// 3. Use F5 to preview or F6 to render
// 4. Export as STL or other 3D format

pixel_size = ${pixelSize};
layer_height = ${height};
image_width = ${image.width};
image_height = ${image.height};

module color_layer(mask_file, color) {
    color(color)
    linear_extrude(height = layer_height)
    scale([pixel_size, pixel_size, 1])
    surface(file = mask_file, center = false, invert = true);
}

// Union all color layers
union() {
`;
    
    // Add layers for each color
    for (let colorIdx = 0; colorIdx < image.partList.length; colorIdx++) {
        const part = image.partList[colorIdx];
        if (!part) continue;
        
        const safeName = part.name.replace(/[^a-zA-Z0-9]/g, '_');
        const r = part.color.r / 255;
        const g = part.color.g / 255;
        const b = part.color.b / 255;
        
        scadCode += `    // ${part.name}\n`;
        scadCode += `    color_layer("${filename}_mask_${colorIdx}_${safeName}.png", [${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)}]);\n`;
    }
    
    scadCode += `}\n`;
    
    return scadCode;
}
