import { PartListImage } from "./image-utils";
import { colorEntryToHex } from "./utils";

export interface OpenSCADMasksSettings {
    pixelHeight: number;
    baseHeight: number;
    imageScale: number;
}

export async function generateOpenSCADMasks(
    image: PartListImage,
    settings: OpenSCADMasksSettings
): Promise<Blob> {
    const { pixelHeight, baseHeight, imageScale } = settings;
    
    // Use JSZip for creating the ZIP file
    const JSZip = await loadJSZip();
    const zip = new JSZip();
    
    // Generate a mask image for each color
    for (let colorIndex = 0; colorIndex < image.partList.length; colorIndex++) {
        const entry = image.partList[colorIndex];
        const maskImage = await generateMaskImage(image, colorIndex);
        const filename = `mask_${sanitizeFilename(entry.target.name)}_${colorIndex}.png`;
        zip.file(filename, maskImage);
    }
    
    // Generate the OpenSCAD file
    const scadContent = generateOpenSCADFile(image, pixelHeight, baseHeight, imageScale);
    zip.file('display.scad', scadContent);
    
    // Generate a README
    const readme = generateReadme(image, settings);
    zip.file('README.txt', readme);
    
    return zip.generateAsync({ type: 'blob' });
}

function generateMaskImage(image: PartListImage, colorIndex: number): Promise<Blob> {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    // Fill with white (empty)
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, image.width, image.height);
    
    // Draw black pixels where this color appears
    ctx.fillStyle = '#000000';
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            if (image.pixels[y][x] === colorIndex) {
                ctx.fillRect(x, y, 1, 1);
            }
        }
    }
    
    // Convert canvas to blob
    return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob(blob => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to create blob from canvas'));
            }
        }, 'image/png');
    });
}

function generateOpenSCADFile(
    image: PartListImage,
    pixelHeight: number,
    baseHeight: number,
    imageScale: number
): string {
    const lines: string[] = [];
    
    lines.push('// Generated by firaga.io - 3D Output');
    lines.push('// OpenSCAD file for creating a 3D display of the pixel art');
    lines.push('');
    lines.push('// Parameters');
    lines.push(`pixel_height = ${pixelHeight};`);
    lines.push(`base_height = ${baseHeight};`);
    lines.push(`image_width = ${image.width};`);
    lines.push(`image_height = ${image.height};`);
    lines.push(`image_scale = ${imageScale};`);
    lines.push('');
    lines.push('// Create base');
    lines.push('color("gray")');
    lines.push('  translate([0, 0, -base_height])');
    lines.push('    cube([image_width * image_scale, image_height * image_scale, base_height]);');
    lines.push('');
    lines.push('// Stack each color layer');
    
    image.partList.forEach((entry, colorIndex) => {
        const colorHex = colorEntryToHex(entry.target);
        const r = entry.target.r / 255;
        const g = entry.target.g / 255;
        const b = entry.target.b / 255;
        const filename = `mask_${sanitizeFilename(entry.target.name)}_${colorIndex}.png`;
        
        lines.push('');
        lines.push(`// ${entry.target.name}`);
        lines.push(`color([${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)}])`);
        lines.push(`  scale([image_scale, image_scale, pixel_height])`);
        lines.push(`    surface(file = "${filename}", center = false, invert = true);`);
    });
    
    return lines.join('\n');
}

function generateReadme(image: PartListImage, settings: OpenSCADMasksSettings): string {
    return `3D OpenSCAD Masks Export
Generated by firaga.io

This package contains:
- One PNG mask file per color (${image.partList.length} colors total)
- An OpenSCAD file (display.scad) that combines them into a 3D model

Settings used:
- Pixel height: ${settings.pixelHeight}mm
- Base height: ${settings.baseHeight}mm
- Image scale: ${settings.imageScale}
- Image dimensions: ${image.width} x ${image.height} pixels

To use:
1. Install OpenSCAD (https://openscad.org/)
2. Open display.scad in OpenSCAD
3. Press F5 to preview or F6 to render
4. Export as STL for 3D printing

Colors included:
${image.partList.map((entry, i) => `${i + 1}. ${entry.target.name} (${entry.count} pixels)`).join('\n')}
`;
}

function sanitizeFilename(name: string): string {
    return name
        .replace(/[^a-zA-Z0-9_-]/g, '_')
        .replace(/_+/g, '_')
        .toLowerCase();
}

async function loadJSZip(): Promise<typeof import('jszip')> {
    // Load JSZip from CDN if not already loaded
    if (typeof (window as any).JSZip !== 'undefined') {
        return (window as any).JSZip;
    }
    
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
        script.onload = () => {
            if ((window as any).JSZip) {
                resolve((window as any).JSZip);
            } else {
                reject(new Error('JSZip failed to load'));
            }
        };
        script.onerror = () => reject(new Error('Failed to load JSZip'));
        document.head.appendChild(script);
    });
}
