import { saveAs } from 'file-saver';
import { PartListImage } from './image-utils';

export async function generateOpenSCADMasks(image: PartListImage, pitch: number, filename: string): Promise<void> {
    const zip = await createZip();
    const pixelSize = pitch / 10; // Convert to mm
    const baseHeight = 1.0; // Height per layer in mm
    
    // Generate one black/white mask per color
    const imageFiles: string[] = [];
    for (let colorIndex = 0; colorIndex < image.partList.length; colorIndex++) {
        const part = image.partList[colorIndex];
        const maskFilename = `mask_${colorIndex}_${sanitizeFilename(part.target.name)}.png`;
        imageFiles.push(maskFilename);
        
        const maskImage = await createMaskImage(image, colorIndex);
        await zip.file(maskFilename, maskImage);
    }
    
    // Generate OpenSCAD file
    const scadContent = generateOpenSCADFile(imageFiles, image.partList, pixelSize, baseHeight, image.width, image.height);
    await zip.file(`${filename}.scad`, scadContent);
    
    // Add README
    const readme = generateReadme(filename);
    await zip.file('README.txt', readme);
    
    const blob = await zip.generateAsync({ type: 'blob' });
    saveAs(blob, `${filename}_openscad.zip`);
}

function createMaskImage(image: PartListImage, colorIndex: number): Promise<Blob> {
    const canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    const ctx = canvas.getContext('2d')!;
    
    // Fill with white
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Draw black pixels where this color appears
    ctx.fillStyle = '#000000';
    for (let y = 0; y < image.height; y++) {
        for (let x = 0; x < image.width; x++) {
            if (image.pixels[y][x] === colorIndex) {
                ctx.fillRect(x, y, 1, 1);
            }
        }
    }
    
    // Convert canvas to blob
    return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error('Failed to create image blob'));
            }
        }, 'image/png');
    });
}

function generateOpenSCADFile(
    imageFiles: string[], 
    partList: PartListImage['partList'],
    pixelSize: number,
    baseHeight: number,
    width: number,
    height: number
): string {
    const colorComments = partList.map((part, i) => 
        `// Layer ${i}: ${part.target.name} (${part.count} pixels)`
    ).join('\n');
    
    const layers = imageFiles.map((filename, i) => {
        const part = partList[i];
        // Convert RGB to 0-1 range for OpenSCAD
        const r = (part.target.r / 255).toFixed(3);
        const g = (part.target.g / 255).toFixed(3);
        const b = (part.target.b / 255).toFixed(3);
        
        return `  // ${part.target.name}
  color([${r}, ${g}, ${b}])
    translate([0, 0, ${i * baseHeight}])
      surface(file = "${filename}", center = true, invert = true, convexity = 5);`;
    }).join('\n\n');
    
    return `// Generated by firaga.io
// Pixel art 3D model using heightmap surfaces
//
// Color layers:
${colorComments}

// Image dimensions
image_width = ${width};
image_height = ${height};
pixel_size = ${pixelSize}; // mm
layer_height = ${baseHeight}; // mm

// Scale factor to convert image to desired size
scale_factor = pixel_size;

scale([scale_factor, scale_factor, layer_height]) {
${layers}
}
`;
}

function generateReadme(filename: string): string {
    return `OpenSCAD 3D Export from firaga.io
Generated: ${new Date().toISOString()}
Project: ${filename}

CONTENTS:
- ${filename}.scad: OpenSCAD source file
- mask_*.png: Black and white mask images (one per color)
- README.txt: This file

INSTRUCTIONS:
1. Install OpenSCAD from https://openscad.org/
2. Open ${filename}.scad in OpenSCAD
3. Press F5 to preview the model
4. Press F6 to render the model
5. Export as STL using File > Export > Export as STL

NOTES:
- Each mask image represents one color layer
- Black pixels in the mask indicate where that color appears
- The OpenSCAD file uses the surface() function to extrude each mask
- Colors are set to match the original palette
- Adjust pixel_size and layer_height variables in the .scad file to change dimensions

For more information, visit https://firaga.io
`;
}

function sanitizeFilename(name: string): string {
    return name
        .replace(/[^a-zA-Z0-9_-]/g, '_')
        .replace(/_+/g, '_')
        .toLowerCase();
}

// Minimal ZIP creation using JSZip (shared with 3MF generator)
async function createZip(): Promise<any> {
    // Check if JSZip is available
    if (typeof (window as any).JSZip !== 'undefined') {
        return new (window as any).JSZip();
    }
    
    // Fallback: load JSZip from CDN
    await loadJSZip();
    return new (window as any).JSZip();
}

async function loadJSZip(): Promise<void> {
    return new Promise((resolve, reject) => {
        if (typeof (window as any).JSZip !== 'undefined') {
            resolve();
            return;
        }
        
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('Failed to load JSZip'));
        document.head.appendChild(script);
    });
}
